[package]
name = "rust_sample"
version = "0.1.0"
authors = ["anthony <antonsdl@gmail.com>"]

[dependencies]
regex = "0.2"
rocket = "0.3.5"
rocket_codegen = "0.3.5"
rocket_contrib = "0.3.5"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"