version: '2'

services:
  jinx:
    image: jinx
    #build: ./nginx
    ports:
      - "443:443"
    restart: always
    depends_on:
      - gopro
      - rocket

  gopro:
      image: gopro
      #build: ./middleware
      environment:
        - SELF_ADDR=0.0.0.0:5000
        - TARGET_ADDR=rocket:8000
      ports:
        - "5000:5000"
      restart: always
      depends_on:
        - rocket

  # gopro and rocket should have same shared volume to share STLs
  rocket:
    image: rocket
    #build: ./backend
    environment:
      - ROCKET_ENV=production
    ports:
      - "8000:8000"
    restart: always
