version: '2'

services:
  jinx:
#    image: jinx
    build: ./nginx
    ports:
      - "443:443"
    restart: always
    depends_on:
      - gopro
      - rocket

  gopro:
#      image: gopro
      build: ./middleware
      environment:
        - SELF_ADDR=0.0.0.0:5000
        - TARGET_ADDR=rocket:8000
      ports:
        - "5000:5000"
      restart: always
      depends_on:
        - rocket
      volumes:
        - stl-folder:/tmp

  # TODO add env var pointing to where save to and read STL from
  rocket:
#    image: rocket
    build: ./backend
    environment:
      - ROCKET_ENV=production
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - stl-folder:/tmp

volumes:
  stl-folder: