[development]
address = "localhost"
port = 8000
workers = 4
log = "normal"
limits = { forms = 32768, json = 5242880 }

[production]
address = "localhost"
port = 5000
workers = 4
log = "normal"
limits = { forms = 32768, json = 5242880 }
